### ISSUE TITLE
nginx log folder doesn't exist

### ISSUE THREAD

**Issue by JeroenvdV** [cwbit/cakephp-docker#1]
On starting the container I see:

`dbta2-nginx      | nginx: [emerg] open() "/var/www/dbta2/logs/access.log" failed (2: No such file or directory)`

This can be fixed by creating the logs folder in your 'cakephp' folder, but there is no mention of this in the README.

**Comment by cwbit** [comment]
This happened because you didn't completely (or properly) install CakePHP (e.g. didn't install with `composer create-project cakephp/app ..`)

I added it to the Troubleshooting section anyway.
